[package]
name = "neoui"
version = "0.1.0"
edition = "2024"

[dependencies]
fontdue = { git = "https://github.com/zfphex/fontdue", default-features = false, features = ["simd"] }
mini = { git = "https://github.com/zfphex/mini", version = "0.1.0", features = ["profile"] }
rustc-hash = "2.1.2"
divan = { version = "0.1.21", optional = true }
criterion = { version = "0.5", features = ["html_reports"], optional = true  }
# minwin = { git = "https://github.com/zfphex/minwin", version = "0.1.0" }
minwin = { version = "0.1.0", path = "../minwin" }
zune-core = { version = "0.5.1", optional = true }
zune-jpeg = { version = "0.5.15", optional = true }
zune-png = { version = "0.5.2", optional = true }

[features]
profile = ["mini/profile"]
bench = ["divan", "criterion"]
jpeg = ["dep:zune-jpeg", "dep:zune-core"]
png = ["dep:zune-png", "dep:zune-core"]
image = ["jpeg", "png"]

[[example]]
name = "image"
required-features = ["image"]

[[bench]]
name = "font"
harness = false
required-features = ["bench"]

[[bench]]
name = "rect"
harness = false
required-features = ["bench"]

[[bench]]
name = "cache"
harness = false
required-features = ["bench"]

[[bench]]
name = "scroll"
harness = false
required-features = ["bench"]

[[bench]]
name = "raster"
harness = false
required-features = ["bench"]

[[bench]]
name = "image"
harness = false
required-features = ["bench"]

[[bench]]
name = "hash"
harness = false
required-features = ["bench"]

[[bench]]
name = "draw_rect_fill"
harness = false
required-features = ["bench"]
